# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, jhuan333/ci_setup, jhuan333/passing_tests, hbach003_failing_tests ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Run a one-line script
        run: echo Hello, world!


      - name: Run test
        run: |
                cmake .
                make
                ./test   
